ip=127.0.0.1

port=5001

#身份证书，仅支持cer格式
ssl_certfile=etc/ssl/server.cer

#私钥文件，仅支持pem格式
ssl_keyfile=etc/ssl/server_key.pem

#私钥文件密码
ssl_keyfile_password=etc/ssl/cert_pwd

#信任证书，仅支持cer格式
ssl_ca_certs=etc/ssl/trust.cer

#校验对端证书
verify_client=true

forwarded_allow_ips="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
